### ISSUE TITLE
Typo: Missing "if" 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/orm-find-or-create-by#12]
The second line needs the word "if". 

*********
"We have two records that contain the same information! How can we avoid this? When we try to save a new Song instance, we should first check to see the object we are trying to save already has an equivalent record in the database, if it does, we should simply update it, otherwise, we can go ahead and save it."

**Comment by sgharms** [comment]
Done! But some grammarians would contend the proper word is "whether" since we're doing a binary choice.
