### ISSUE TITLE
Grammar: Noun/Verb Agreement 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/orm-find-or-create-by#13]
Should be "...each of which has the exact...."  
Verb has to agree with word 'each'. The 'of which' is a prepositional phrase that doesn't determine the verb.  

**************
Nothing stops us from creating two objects, each of which have the exact same name and album.

**Comment by ccklight** [comment]
Thanks for the updates. FYI, intention is not to be a pain but to make FI
be the best!  Luv Flatiron.

**Comment by sgharms** [comment]
No problem, CC. Thanks for the help.
