### ISSUE TITLE
Grammar: Run-On Sentence 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/orm-find-or-create-by#14]
Should be a . after database.   
Otherwise, this is a run-on sentence. It has two independent clauses which can function on their own that are incorrectly separated by a comma.    Also, don't forget the missing 'if'.  

**********
"....we should first check to see the object we are trying to save already has an equivalent record in the database, if it does, we should simply update it, otherwise, we can go ahead and save it."

**Comment by sgharms** [comment]
Fixed!
